server:
  port: 8081
spring:
  application:
    name: SpringCloudStream-Producer

  cloud:
    function:
      definition: processorBinding;consumerBinding # producerBinding;
    stream:
      bindings:
#        producerBinding-out-0:
#          destination:
        processorBinding-in-0:
          destination: in-of-prod
        processorBinding-out-0:
          destination: consumer-of-prod
        consumerBinding-in-0:
          destination: consumer-of-prod
      kafka:
        binder:
          applicationId: producer-app
          brokers: localhost:9092
#          configuration:
#            default:
#              key:
#                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#              value:
#                serde: org.apache.kafka.common.serialization.Serdes$StringSerde


